server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems?createDatabaseIfNotExist=true
    username: root
    password: Niki@23
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update



